//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBADetsisIntegration.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryStringLoginParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryStringLoginParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool TopBarVisibleField;
        
        private bool LeftMenuVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessFilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParametersField;
        
        private bool DisableEBA3Field;
        
        private bool MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelegationFromField;
        
        private int DelegationFromTypeField;
        
        private bool DelegatedField;
        
        private System.Nullable<int> DelegationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceSystemField;
        
        private bool TestModeField;
        
        private bool LeftMenuCollapsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        private int ClickCountField;
        
        private long ExpireDateTickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivePositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool TopBarVisible {
            get {
                return this.TopBarVisibleField;
            }
            set {
                if ((this.TopBarVisibleField.Equals(value) != true)) {
                    this.TopBarVisibleField = value;
                    this.RaisePropertyChanged("TopBarVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool LeftMenuVisible {
            get {
                return this.LeftMenuVisibleField;
            }
            set {
                if ((this.LeftMenuVisibleField.Equals(value) != true)) {
                    this.LeftMenuVisibleField = value;
                    this.RaisePropertyChanged("LeftMenuVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProcessFilter {
            get {
                return this.ProcessFilterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessFilterField, value) != true)) {
                    this.ProcessFilterField = value;
                    this.RaisePropertyChanged("ProcessFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool DisableEBA3 {
            get {
                return this.DisableEBA3Field;
            }
            set {
                if ((this.DisableEBA3Field.Equals(value) != true)) {
                    this.DisableEBA3Field = value;
                    this.RaisePropertyChanged("DisableEBA3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((this.MobileField.Equals(value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DelegationFrom {
            get {
                return this.DelegationFromField;
            }
            set {
                if ((object.ReferenceEquals(this.DelegationFromField, value) != true)) {
                    this.DelegationFromField = value;
                    this.RaisePropertyChanged("DelegationFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int DelegationFromType {
            get {
                return this.DelegationFromTypeField;
            }
            set {
                if ((this.DelegationFromTypeField.Equals(value) != true)) {
                    this.DelegationFromTypeField = value;
                    this.RaisePropertyChanged("DelegationFromType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Delegated {
            get {
                return this.DelegatedField;
            }
            set {
                if ((this.DelegatedField.Equals(value) != true)) {
                    this.DelegatedField = value;
                    this.RaisePropertyChanged("Delegated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> DelegationId {
            get {
                return this.DelegationIdField;
            }
            set {
                if ((this.DelegationIdField.Equals(value) != true)) {
                    this.DelegationIdField = value;
                    this.RaisePropertyChanged("DelegationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SourceSystem {
            get {
                return this.SourceSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceSystemField, value) != true)) {
                    this.SourceSystemField = value;
                    this.RaisePropertyChanged("SourceSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool TestMode {
            get {
                return this.TestModeField;
            }
            set {
                if ((this.TestModeField.Equals(value) != true)) {
                    this.TestModeField = value;
                    this.RaisePropertyChanged("TestMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool LeftMenuCollapsed {
            get {
                return this.LeftMenuCollapsedField;
            }
            set {
                if ((this.LeftMenuCollapsedField.Equals(value) != true)) {
                    this.LeftMenuCollapsedField = value;
                    this.RaisePropertyChanged("LeftMenuCollapsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int ClickCount {
            get {
                return this.ClickCountField;
            }
            set {
                if ((this.ClickCountField.Equals(value) != true)) {
                    this.ClickCountField = value;
                    this.RaisePropertyChanged("ClickCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public long ExpireDateTick {
            get {
                return this.ExpireDateTickField;
            }
            set {
                if ((this.ExpireDateTickField.Equals(value) != true)) {
                    this.ExpireDateTickField = value;
                    this.RaisePropertyChanged("ExpireDateTick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ActivePosition {
            get {
                return this.ActivePositionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivePositionField, value) != true)) {
                    this.ActivePositionField = value;
                    this.RaisePropertyChanged("ActivePosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.QueryStringLoginSoap")]
    public interface QueryStringLoginSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLogin", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse GetQueryStringLogin(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse> GetQueryStringLoginAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginWithParameters", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse GetQueryStringLoginWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse> GetQueryStringLoginWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginAsWithParameters", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse GetQueryStringLoginAsWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginAsWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse> GetQueryStringLoginAsWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginDelegatedWithParameters", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse GetQueryStringLoginDelegatedWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQueryStringLoginDelegatedWithParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse> GetQueryStringLoginDelegatedWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExternalUserId", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse GetExternalUserId(eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExternalUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse> GetExternalUserIdAsync(eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInternalUserId", ReplyAction="*")]
        eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse GetInternalUserId(eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInternalUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse> GetInternalUserIdAsync(eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLogin", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequestBody Body;
        
        public GetQueryStringLoginRequest() {
        }
        
        public GetQueryStringLoginRequest(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        public GetQueryStringLoginRequestBody() {
        }
        
        public GetQueryStringLoginRequestBody(string user, string password, string logonuser) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponseBody Body;
        
        public GetQueryStringLoginResponse() {
        }
        
        public GetQueryStringLoginResponse(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQueryStringLoginResult;
        
        public GetQueryStringLoginResponseBody() {
        }
        
        public GetQueryStringLoginResponseBody(string GetQueryStringLoginResult) {
            this.GetQueryStringLoginResult = GetQueryStringLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginWithParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginWithParameters", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequestBody Body;
        
        public GetQueryStringLoginWithParametersRequest() {
        }
        
        public GetQueryStringLoginWithParametersRequest(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginWithParametersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters;
        
        public GetQueryStringLoginWithParametersRequestBody() {
        }
        
        public GetQueryStringLoginWithParametersRequestBody(string user, string password, string logonuser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginWithParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginWithParametersResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponseBody Body;
        
        public GetQueryStringLoginWithParametersResponse() {
        }
        
        public GetQueryStringLoginWithParametersResponse(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginWithParametersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQueryStringLoginWithParametersResult;
        
        public GetQueryStringLoginWithParametersResponseBody() {
        }
        
        public GetQueryStringLoginWithParametersResponseBody(string GetQueryStringLoginWithParametersResult) {
            this.GetQueryStringLoginWithParametersResult = GetQueryStringLoginWithParametersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginAsWithParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginAsWithParameters", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequestBody Body;
        
        public GetQueryStringLoginAsWithParametersRequest() {
        }
        
        public GetQueryStringLoginAsWithParametersRequest(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginAsWithParametersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatingUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters;
        
        public GetQueryStringLoginAsWithParametersRequestBody() {
        }
        
        public GetQueryStringLoginAsWithParametersRequestBody(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
            this.impersonatingUser = impersonatingUser;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginAsWithParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginAsWithParametersResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponseBody Body;
        
        public GetQueryStringLoginAsWithParametersResponse() {
        }
        
        public GetQueryStringLoginAsWithParametersResponse(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginAsWithParametersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQueryStringLoginAsWithParametersResult;
        
        public GetQueryStringLoginAsWithParametersResponseBody() {
        }
        
        public GetQueryStringLoginAsWithParametersResponseBody(string GetQueryStringLoginAsWithParametersResult) {
            this.GetQueryStringLoginAsWithParametersResult = GetQueryStringLoginAsWithParametersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginDelegatedWithParametersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginDelegatedWithParameters", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequestBody Body;
        
        public GetQueryStringLoginDelegatedWithParametersRequest() {
        }
        
        public GetQueryStringLoginDelegatedWithParametersRequest(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginDelegatedWithParametersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string impersonatingUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters;
        
        public GetQueryStringLoginDelegatedWithParametersRequestBody() {
        }
        
        public GetQueryStringLoginDelegatedWithParametersRequestBody(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
            this.impersonatingUser = impersonatingUser;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQueryStringLoginDelegatedWithParametersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQueryStringLoginDelegatedWithParametersResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponseBody Body;
        
        public GetQueryStringLoginDelegatedWithParametersResponse() {
        }
        
        public GetQueryStringLoginDelegatedWithParametersResponse(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQueryStringLoginDelegatedWithParametersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetQueryStringLoginDelegatedWithParametersResult;
        
        public GetQueryStringLoginDelegatedWithParametersResponseBody() {
        }
        
        public GetQueryStringLoginDelegatedWithParametersResponseBody(string GetQueryStringLoginDelegatedWithParametersResult) {
            this.GetQueryStringLoginDelegatedWithParametersResult = GetQueryStringLoginDelegatedWithParametersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExternalUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExternalUserId", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequestBody Body;
        
        public GetExternalUserIdRequest() {
        }
        
        public GetExternalUserIdRequest(eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExternalUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        public GetExternalUserIdRequestBody() {
        }
        
        public GetExternalUserIdRequestBody(string user, string password, string logonuser) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExternalUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExternalUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponseBody Body;
        
        public GetExternalUserIdResponse() {
        }
        
        public GetExternalUserIdResponse(eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExternalUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExternalUserIdResult;
        
        public GetExternalUserIdResponseBody() {
        }
        
        public GetExternalUserIdResponseBody(string GetExternalUserIdResult) {
            this.GetExternalUserIdResult = GetExternalUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInternalUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInternalUserId", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequestBody Body;
        
        public GetInternalUserIdRequest() {
        }
        
        public GetInternalUserIdRequest(eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInternalUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logonuser;
        
        public GetInternalUserIdRequestBody() {
        }
        
        public GetInternalUserIdRequestBody(string user, string password, string logonuser) {
            this.user = user;
            this.password = password;
            this.logonuser = logonuser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInternalUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInternalUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponseBody Body;
        
        public GetInternalUserIdResponse() {
        }
        
        public GetInternalUserIdResponse(eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInternalUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInternalUserIdResult;
        
        public GetInternalUserIdResponseBody() {
        }
        
        public GetInternalUserIdResponseBody(string GetInternalUserIdResult) {
            this.GetInternalUserIdResult = GetInternalUserIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryStringLoginSoapChannel : eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryStringLoginSoapClient : System.ServiceModel.ClientBase<eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap>, eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap {
        
        public QueryStringLoginSoapClient() {
        }
        
        public QueryStringLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryStringLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryStringLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryStringLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLogin(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest request) {
            return base.Channel.GetQueryStringLogin(request);
        }
        
        public string GetQueryStringLogin(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLogin(inValue);
            return retVal.Body.GetQueryStringLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest request) {
            return base.Channel.GetQueryStringLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginResponse> GetQueryStringLoginAsync(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginWithParameters(request);
        }
        
        public string GetQueryStringLoginWithParameters(string user, string password, string logonuser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.parameters = parameters;
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginWithParameters(inValue);
            return retVal.Body.GetQueryStringLoginWithParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginWithParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersResponse> GetQueryStringLoginWithParametersAsync(string user, string password, string logonuser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.parameters = parameters;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginWithParametersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginAsWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginAsWithParameters(request);
        }
        
        public string GetQueryStringLoginAsWithParameters(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.impersonatingUser = impersonatingUser;
            inValue.Body.parameters = parameters;
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginAsWithParameters(inValue);
            return retVal.Body.GetQueryStringLoginAsWithParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginAsWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginAsWithParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersResponse> GetQueryStringLoginAsWithParametersAsync(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginAsWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.impersonatingUser = impersonatingUser;
            inValue.Body.parameters = parameters;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginAsWithParametersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginDelegatedWithParameters(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginDelegatedWithParameters(request);
        }
        
        public string GetQueryStringLoginDelegatedWithParameters(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.impersonatingUser = impersonatingUser;
            inValue.Body.parameters = parameters;
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginDelegatedWithParameters(inValue);
            return retVal.Body.GetQueryStringLoginDelegatedWithParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetQueryStringLoginDelegatedWithParametersAsync(eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest request) {
            return base.Channel.GetQueryStringLoginDelegatedWithParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersResponse> GetQueryStringLoginDelegatedWithParametersAsync(string user, string password, string logonuser, string impersonatingUser, eBADetsisIntegration.ServiceReference2.QueryStringLoginParameters parameters) {
            eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest inValue = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetQueryStringLoginDelegatedWithParametersRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            inValue.Body.impersonatingUser = impersonatingUser;
            inValue.Body.parameters = parameters;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetQueryStringLoginDelegatedWithParametersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetExternalUserId(eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest request) {
            return base.Channel.GetExternalUserId(request);
        }
        
        public string GetExternalUserId(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest inValue = new eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetExternalUserId(inValue);
            return retVal.Body.GetExternalUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetExternalUserIdAsync(eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest request) {
            return base.Channel.GetExternalUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetExternalUserIdResponse> GetExternalUserIdAsync(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest inValue = new eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetExternalUserIdRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetExternalUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetInternalUserId(eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest request) {
            return base.Channel.GetInternalUserId(request);
        }
        
        public string GetInternalUserId(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest inValue = new eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse retVal = ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetInternalUserId(inValue);
            return retVal.Body.GetInternalUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse> eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap.GetInternalUserIdAsync(eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest request) {
            return base.Channel.GetInternalUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBADetsisIntegration.ServiceReference2.GetInternalUserIdResponse> GetInternalUserIdAsync(string user, string password, string logonuser) {
            eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest inValue = new eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequest();
            inValue.Body = new eBADetsisIntegration.ServiceReference2.GetInternalUserIdRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.logonuser = logonuser;
            return ((eBADetsisIntegration.ServiceReference2.QueryStringLoginSoap)(this)).GetInternalUserIdAsync(inValue);
        }
    }
}
