//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GetDetsisConsole.DetsisSrv {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegrationSoap", Namespace="http://tempuri.org/")]
    public partial class Integration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDetsisOperationCompleted;
        
        private System.Threading.SendOrPostCallback YerBilgisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback eBADETSISNoKurumBirimWsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdaGoreKurumBirimSorgulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback KurumIletisimBilgileriOperationCompleted;
        
        private System.Threading.SendOrPostCallback HiyerarsiGetirKurumBirimOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Integration() {
            this.Url = global::GetDetsisConsole.Properties.Settings.Default.GetDetsisConsole_DetsisSrv_Integration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDetsisCompletedEventHandler GetDetsisCompleted;
        
        /// <remarks/>
        public event YerBilgisiCompletedEventHandler YerBilgisiCompleted;
        
        /// <remarks/>
        public event eBADETSISNoKurumBirimWsCompletedEventHandler eBADETSISNoKurumBirimWsCompleted;
        
        /// <remarks/>
        public event AdaGoreKurumBirimSorgulaCompletedEventHandler AdaGoreKurumBirimSorgulaCompleted;
        
        /// <remarks/>
        public event KurumIletisimBilgileriCompletedEventHandler KurumIletisimBilgileriCompleted;
        
        /// <remarks/>
        public event HiyerarsiGetirKurumBirimCompletedEventHandler HiyerarsiGetirKurumBirimCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDetsis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDetsis() {
            this.Invoke("GetDetsis", new object[0]);
        }
        
        /// <remarks/>
        public void GetDetsisAsync() {
            this.GetDetsisAsync(null);
        }
        
        /// <remarks/>
        public void GetDetsisAsync(object userState) {
            if ((this.GetDetsisOperationCompleted == null)) {
                this.GetDetsisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetsisOperationCompleted);
            }
            this.InvokeAsync("GetDetsis", new object[0], this.GetDetsisOperationCompleted, userState);
        }
        
        private void OnGetDetsisOperationCompleted(object arg) {
            if ((this.GetDetsisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetsisCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YerBilgisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void YerBilgisi() {
            this.Invoke("YerBilgisi", new object[0]);
        }
        
        /// <remarks/>
        public void YerBilgisiAsync() {
            this.YerBilgisiAsync(null);
        }
        
        /// <remarks/>
        public void YerBilgisiAsync(object userState) {
            if ((this.YerBilgisiOperationCompleted == null)) {
                this.YerBilgisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYerBilgisiOperationCompleted);
            }
            this.InvokeAsync("YerBilgisi", new object[0], this.YerBilgisiOperationCompleted, userState);
        }
        
        private void OnYerBilgisiOperationCompleted(object arg) {
            if ((this.YerBilgisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YerBilgisiCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eBADETSISNoKurumBirimWs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable eBADETSISNoKurumBirimWs(int kurumId) {
            object[] results = this.Invoke("eBADETSISNoKurumBirimWs", new object[] {
                        kurumId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void eBADETSISNoKurumBirimWsAsync(int kurumId) {
            this.eBADETSISNoKurumBirimWsAsync(kurumId, null);
        }
        
        /// <remarks/>
        public void eBADETSISNoKurumBirimWsAsync(int kurumId, object userState) {
            if ((this.eBADETSISNoKurumBirimWsOperationCompleted == null)) {
                this.eBADETSISNoKurumBirimWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OneBADETSISNoKurumBirimWsOperationCompleted);
            }
            this.InvokeAsync("eBADETSISNoKurumBirimWs", new object[] {
                        kurumId}, this.eBADETSISNoKurumBirimWsOperationCompleted, userState);
        }
        
        private void OneBADETSISNoKurumBirimWsOperationCompleted(object arg) {
            if ((this.eBADETSISNoKurumBirimWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eBADETSISNoKurumBirimWsCompleted(this, new eBADETSISNoKurumBirimWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdaGoreKurumBirimSorgula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AdaGoreKurumBirimSorgula(string Ara, string UstBirimKodu) {
            object[] results = this.Invoke("AdaGoreKurumBirimSorgula", new object[] {
                        Ara,
                        UstBirimKodu});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AdaGoreKurumBirimSorgulaAsync(string Ara, string UstBirimKodu) {
            this.AdaGoreKurumBirimSorgulaAsync(Ara, UstBirimKodu, null);
        }
        
        /// <remarks/>
        public void AdaGoreKurumBirimSorgulaAsync(string Ara, string UstBirimKodu, object userState) {
            if ((this.AdaGoreKurumBirimSorgulaOperationCompleted == null)) {
                this.AdaGoreKurumBirimSorgulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdaGoreKurumBirimSorgulaOperationCompleted);
            }
            this.InvokeAsync("AdaGoreKurumBirimSorgula", new object[] {
                        Ara,
                        UstBirimKodu}, this.AdaGoreKurumBirimSorgulaOperationCompleted, userState);
        }
        
        private void OnAdaGoreKurumBirimSorgulaOperationCompleted(object arg) {
            if ((this.AdaGoreKurumBirimSorgulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdaGoreKurumBirimSorgulaCompleted(this, new AdaGoreKurumBirimSorgulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KurumIletisimBilgileri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable KurumIletisimBilgileri(string detsisNo) {
            object[] results = this.Invoke("KurumIletisimBilgileri", new object[] {
                        detsisNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void KurumIletisimBilgileriAsync(string detsisNo) {
            this.KurumIletisimBilgileriAsync(detsisNo, null);
        }
        
        /// <remarks/>
        public void KurumIletisimBilgileriAsync(string detsisNo, object userState) {
            if ((this.KurumIletisimBilgileriOperationCompleted == null)) {
                this.KurumIletisimBilgileriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKurumIletisimBilgileriOperationCompleted);
            }
            this.InvokeAsync("KurumIletisimBilgileri", new object[] {
                        detsisNo}, this.KurumIletisimBilgileriOperationCompleted, userState);
        }
        
        private void OnKurumIletisimBilgileriOperationCompleted(object arg) {
            if ((this.KurumIletisimBilgileriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KurumIletisimBilgileriCompleted(this, new KurumIletisimBilgileriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HiyerarsiGetirKurumBirim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable HiyerarsiGetirKurumBirim(string DetsisNo) {
            object[] results = this.Invoke("HiyerarsiGetirKurumBirim", new object[] {
                        DetsisNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void HiyerarsiGetirKurumBirimAsync(string DetsisNo) {
            this.HiyerarsiGetirKurumBirimAsync(DetsisNo, null);
        }
        
        /// <remarks/>
        public void HiyerarsiGetirKurumBirimAsync(string DetsisNo, object userState) {
            if ((this.HiyerarsiGetirKurumBirimOperationCompleted == null)) {
                this.HiyerarsiGetirKurumBirimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHiyerarsiGetirKurumBirimOperationCompleted);
            }
            this.InvokeAsync("HiyerarsiGetirKurumBirim", new object[] {
                        DetsisNo}, this.HiyerarsiGetirKurumBirimOperationCompleted, userState);
        }
        
        private void OnHiyerarsiGetirKurumBirimOperationCompleted(object arg) {
            if ((this.HiyerarsiGetirKurumBirimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HiyerarsiGetirKurumBirimCompleted(this, new HiyerarsiGetirKurumBirimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetDetsisCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void YerBilgisiCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void eBADETSISNoKurumBirimWsCompletedEventHandler(object sender, eBADETSISNoKurumBirimWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eBADETSISNoKurumBirimWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eBADETSISNoKurumBirimWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AdaGoreKurumBirimSorgulaCompletedEventHandler(object sender, AdaGoreKurumBirimSorgulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdaGoreKurumBirimSorgulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdaGoreKurumBirimSorgulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void KurumIletisimBilgileriCompletedEventHandler(object sender, KurumIletisimBilgileriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KurumIletisimBilgileriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KurumIletisimBilgileriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HiyerarsiGetirKurumBirimCompletedEventHandler(object sender, HiyerarsiGetirKurumBirimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HiyerarsiGetirKurumBirimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HiyerarsiGetirKurumBirimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591