//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetsisTest.ATSO {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATSO.IntegrationSoap")]
    public interface IntegrationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kurumAdinaGoreSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable kurumAdinaGoreSorgula(string key, int parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kurumAdinaGoreSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> kurumAdinaGoreSorgulaAsync(string key, int parent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IntegrationSoapChannel : DetsisTest.ATSO.IntegrationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationSoapClient : System.ServiceModel.ClientBase<DetsisTest.ATSO.IntegrationSoap>, DetsisTest.ATSO.IntegrationSoap {
        
        public IntegrationSoapClient() {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable kurumAdinaGoreSorgula(string key, int parent) {
            return base.Channel.kurumAdinaGoreSorgula(key, parent);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> kurumAdinaGoreSorgulaAsync(string key, int parent) {
            return base.Channel.kurumAdinaGoreSorgulaAsync(key, parent);
        }
    }
}
